### ISSUE TITLE
No files listed in the report

### ISSUE THREAD

**Issue by ecton** [dnaka91/llvm-cov-pretty#1] opened 2023-06-19 13:58 UTC
### Describe the bug

I ran `cargo install llvm-cov-pretty`, and then tried with a project without a workspace as well as a project with a workspace. In both, the report generated contains the correct overview information, but there are no files listed to poke into. The target folder only contains index.html, style.css, and syntax.css.

### Expected behavior

I expected beautiful results like you shared in discord! :)

### To reproduce

1. Clone https://github.com/khonsulabs/alot
2. Execute `cargo llvm-cov --json | llvm-cov-pretty`
3. Open the report

### What operating system are you using?

None

### Additional context

Because my output for llvm-cov may be different (why? I don't know!) I've uploaded the json output in [this gist](https://gist.github.com/ecton/fd1db4811bb3d3dbde719530fa179cd2).

**Comment by dnaka91** [comment] 2023-06-20 03:47
It works fine for me, but I noticed that your JSON output doesn't use absolute paths. Instead, file paths are relative to the project root.

I remember `cargo-llvm-cov` did path adjustments in the past, and there was a bit of a forth and back about that feature. But this can be caused by custom cargo configuration as well.

- Could it be that your `cargo-llvm-cov` version is a bit dated? Mine is `0.5.20`.
- Do you use a global config for `cargo-llvm-cov`? Although, I don't think there is any config option beyond cli flags and env vars.
- Do you have some global cargo config, that makes use of the `remap-path-prefix` setting? That would be some `rustflags` setting that contains `--remap-path-prefix` in `~/.cargo/config.toml` or eventually through env vars.

This looks hard to detect, as I'd have to wrap `cargo-llvm-cov` to catch any extra args and react to them, and likely use some unstable cargo features to get the currently active config and use it to detect path rewrites.

Maybe for a starter it's worth doing a double lookup, as it's probably a common case to remap paths to the project root (that's what `cargo-llvm-cov` does if you pass it the `--remap-path-prefix` option). So I'd look up both the absolute and relative path when mapping project files to coverage data.

**Comment by ecton** [comment] 2023-06-20 14:21
Oops, I hadn't updated `cargo-llvm-cov` in quite some time -- it was at 0.2.1. I don't have any custom configurations. I would just close this out of my own stupidity, but I'll leave the issue open in case you want to add some version check to prevent other people like me who never remember to update the things they `cargo install`.

**Comment by dnaka91** [comment] 2023-06-20 16:54
Yeah, let's leave it open. I'll do both:
- Add support for relative paths (to support the `--remap-path-prefix` flag of `cargo-llvm-cov`, which would cause the same behavior as the older version).
- Invoke `cargo-llvm-cov` once at the start, to extract the version number and check that it's at least a known to be working version.

**Comment by dnaka91** [comment] 2023-06-22 14:44
Okay, with the latest release I did a few hours ago, these things should be fixed by implementing the two points mentioned in my previous message.

I'll close this for now, but in case that problem occurs again, don't hesitate to re-open it :+1:

**Closed by dnaka91** 2023-06-22 14:44 UTC
Labels: bug
